language: ruby
sudo: false
rvm:
  - 2.2.3
bundler_args: "--without development production --deployment --jobs=3 --retry=3"
cache: :bundler
before_script:
  - psql -c 'create database handy_test;' -U postgres
env:
  - TWILIO_ACCOUNT_SID=12345 TWILIO_AUTH_TOKEN=abcdefg
notifications:
  email: false
  slack:
    secure: KSg+Em4mi7dCyWrPehv2ZehK6ujz9puI3V5fje6erpt/g2oiXdxo8enniTgtobZ3pacbpJ9LcPfxiqr2nRoUZfA5R/aFMkgIJANIYweHG10Ny41Uo4GjQGZLjf2brJTFk30ySAyGl7+F5QppA+ob7jp5mI2RwhvI9fC+YaX5GN8=
