language: ruby
rvm:
  - 2.1.2
bundler_args: "--without development production --deployment --jobs=3 --retry=3"
before_script:
  - mysql -e 'CREATE DATABASE handy_test'
  - cp config/database.yml.sample config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/twilio.yml.sample config/twilio.yml
notifications:
  email: false
  slack:
    secure: KSg+Em4mi7dCyWrPehv2ZehK6ujz9puI3V5fje6erpt/g2oiXdxo8enniTgtobZ3pacbpJ9LcPfxiqr2nRoUZfA5R/aFMkgIJANIYweHG10Ny41Uo4GjQGZLjf2brJTFk30ySAyGl7+F5QppA+ob7jp5mI2RwhvI9fC+YaX5GN8=
